// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc9jpQuub7mvG2_1W6L3WjXguUU0iLo9c',
    appId: '1:655374288545:web:3c5e2d9e1b76cf225112e0',
    messagingSenderId: '655374288545',
    projectId: 'tyui-9673f',
    authDomain: 'tyui-9673f.firebaseapp.com',
    storageBucket: 'tyui-9673f.firebasestorage.app',
    measurementId: 'G-YM0T20RJH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI-Inlz2-fKNHDetR-D3ygI1FPyqTw0hk',
    appId: '1:655374288545:android:6e841e183e1b91505112e0',
    messagingSenderId: '655374288545',
    projectId: 'tyui-9673f',
    storageBucket: 'tyui-9673f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRjivPvT3AT_oZfLIodotKRcyjjgqtFe8',
    appId: '1:655374288545:ios:287161259ffb20b05112e0',
    messagingSenderId: '655374288545',
    projectId: 'tyui-9673f',
    storageBucket: 'tyui-9673f.firebasestorage.app',
    iosBundleId: 'com.example.farahSysFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc9jpQuub7mvG2_1W6L3WjXguUU0iLo9c',
    appId: '1:655374288545:web:514a4fde2f3a954d5112e0',
    messagingSenderId: '655374288545',
    projectId: 'tyui-9673f',
    authDomain: 'tyui-9673f.firebaseapp.com',
    storageBucket: 'tyui-9673f.firebasestorage.app',
    measurementId: 'G-Z7FNJEB509',
  );
}
